[2017-05-18 18:16:52 basic.lib_net] INFO 获取操作文字成功
[2017-05-18 18:16:54 basic.lib_net] INFO 获取控件路径成功
[2017-05-18 18:16:54 basic.lib_net] INFO 获取操作文字成功
[2017-05-18 18:16:54 basic.lib_net] INFO 获取控件路径成功
[2017-05-18 18:16:54 basic.lib_net] INFO 获取操作文字成功
[2017-05-18 18:16:56 basic.lib_net] INFO 获取控件路径成功
[2017-05-18 18:16:56 basic.lib_net] INFO 获取操作文字成功
[2017-05-18 18:23:14 basic.lib_net] INFO 获取控件路径成功
[2017-05-18 18:23:14 basic.lib_net] INFO 获取操作文字成功
[2017-05-18 18:23:18 basic.lib_net] INFO 获取控件路径成功
[2017-05-18 18:23:18 basic.lib_net] INFO 获取操作文字成功
[2017-05-23 16:25:54 basic.lib_net] ERROR Invoke http://localhost:5005/api/1.0/Report failed, response is False
[2017-05-23 16:25:54 basic.lib_net] ERROR None

[2017-05-23 16:37:23 basic.lib_net] ERROR Invoke http://localhost:5005/api/1.0/Report failed, response is False
[2017-05-23 16:37:23 basic.lib_net] ERROR None

[2017-05-23 16:37:43 basic.lib_net] ERROR Invoke http://localhost:5005/api/1.0/Report failed, response is False
[2017-05-23 16:37:43 basic.lib_net] ERROR None

[2017-05-23 16:41:00 basic.lib_net] ERROR Invoke http://localhost:5005/api/1.0/Report failed, response is False
[2017-05-23 16:41:00 basic.lib_net] ERROR None

[2017-05-23 16:41:01 basic.lib_net] ERROR Invoke http://localhost:5005/api/1.0/Report failed, response is False
[2017-05-23 16:41:01 basic.lib_net] ERROR None

[2017-05-23 16:41:27 basic.lib_net] ERROR Invoke http://localhost:5005/api/1.0/Report failed, response is False
[2017-05-23 16:41:27 basic.lib_net] ERROR None

[2017-05-23 16:41:28 basic.lib_net] ERROR Invoke http://localhost:5005/api/1.0/Report failed, response is False
[2017-05-23 16:41:28 basic.lib_net] ERROR None

[2017-05-23 16:41:31 basic.lib_net] ERROR Invoke http://localhost:5005/api/1.0/Report failed, response is False
[2017-05-23 16:41:31 basic.lib_net] ERROR None

[2017-05-23 16:51:53 basic.lib_net] ERROR Invoke http://localhost:5005/api/1.0/Report failed, response is False
[2017-05-23 16:51:53 basic.lib_net] ERROR None

[2017-05-23 16:51:55 basic.lib_net] ERROR Invoke http://localhost:5005/api/1.0/Report failed, response is False
[2017-05-23 16:51:55 basic.lib_net] ERROR None

[2017-05-23 16:51:56 basic.lib_net] ERROR Invoke http://localhost:5005/api/1.0/Report failed, response is False
[2017-05-23 16:51:56 basic.lib_net] ERROR None

[2017-05-23 16:55:18 basic.lib_net] ERROR Invoke http://localhost:5005/api/1.0/Report failed, response is False
[2017-05-23 16:55:18 basic.lib_net] ERROR None

[2017-05-23 16:55:18 basic.lib_net] ERROR Invoke http://localhost:5005/api/1.0/Report failed, response is False
[2017-05-23 16:55:18 basic.lib_net] ERROR None

[2017-05-23 16:55:19 basic.lib_net] ERROR Invoke http://localhost:5005/api/1.0/Report failed, response is False
[2017-05-23 16:55:19 basic.lib_net] ERROR None

[2017-05-23 16:55:20 basic.lib_net] ERROR Invoke http://localhost:5005/api/1.0/Report failed, response is False
[2017-05-23 16:55:20 basic.lib_net] ERROR None

[2017-05-23 16:55:21 basic.lib_net] ERROR Invoke http://localhost:5005/api/1.0/Report failed, response is False
[2017-05-23 16:55:21 basic.lib_net] ERROR None

[2017-05-23 16:55:22 basic.lib_net] ERROR Invoke http://localhost:5005/api/1.0/Report failed, response is False
[2017-05-23 16:55:22 basic.lib_net] ERROR None

[2017-05-23 16:55:22 basic.lib_net] ERROR Invoke http://localhost:5005/api/1.0/Report failed, response is False
[2017-05-23 16:55:22 basic.lib_net] ERROR None

[2017-05-23 16:55:24 basic.lib_net] ERROR Invoke http://localhost:5005/api/1.0/Report failed, response is False
[2017-05-23 16:55:24 basic.lib_net] ERROR None

[2017-05-23 16:55:25 basic.lib_net] ERROR Invoke http://localhost:5005/api/1.0/Report failed, response is False
[2017-05-23 16:55:25 basic.lib_net] ERROR None

[2017-05-23 16:56:53 basic.lib_net] ERROR Invoke http://localhost:5005/api/1.0/Report failed, response is False
[2017-05-23 16:56:53 basic.lib_net] ERROR None

[2017-05-23 16:56:54 basic.lib_net] ERROR Invoke http://localhost:5005/api/1.0/Report failed, response is False
[2017-05-23 16:56:54 basic.lib_net] ERROR None

[2017-05-23 16:56:56 basic.lib_net] ERROR Invoke http://localhost:5005/api/1.0/Report failed, response is False
[2017-05-23 16:56:56 basic.lib_net] ERROR None

[2017-05-25 15:39:57 basic.lib_net] ERROR Invoke http://localhost:5005/api/1.0/Report failed, response is False
[2017-05-25 15:39:57 basic.lib_net] ERROR None

[2017-05-25 15:39:58 basic.lib_net] ERROR Invoke http://localhost:5005/api/1.0/Report failed, response is False
[2017-05-25 15:39:58 basic.lib_net] ERROR None

[2017-05-25 15:42:57 basic.lib_net] ERROR Invoke http://localhost:5005/api/1.0/Report failed, response is False
[2017-05-25 15:42:57 basic.lib_net] ERROR None

[2017-05-25 15:42:58 basic.lib_net] ERROR Invoke http://localhost:5005/api/1.0/Report failed, response is False
[2017-05-25 15:42:58 basic.lib_net] ERROR None

[2017-05-25 17:34:30 basic.lib_net] ERROR function invoke error: 'module' object has no attribute 'WindowDefAPI'
[2017-05-25 17:34:30 basic.lib_net] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcLib/LibNet.py", line 262, in action
    _module = self.__get_module(p_path)
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcLib/LibNet.py", line 331, in __get_module
    return getattr(__import__(self._path, fromlist=True), _name)()
AttributeError: 'module' object has no attribute 'WindowDefAPI'

[2017-05-25 17:34:32 basic.lib_net] ERROR function invoke error: 'module' object has no attribute 'WindowDefAPI'
[2017-05-25 17:34:32 basic.lib_net] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcLib/LibNet.py", line 262, in action
    _module = self.__get_module(p_path)
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcLib/LibNet.py", line 331, in __get_module
    return getattr(__import__(self._path, fromlist=True), _name)()
AttributeError: 'module' object has no attribute 'WindowDefAPI'

[2017-05-27 09:57:29 basic.lib_net] INFO 获取控件路径成功
[2017-05-27 09:57:29 basic.lib_net] INFO 获取操作文字成功
[2017-06-05 17:06:11 basic.lib_net] INFO 获取页面标识成功
[2017-06-05 17:06:11 basic.lib_net] INFO 获取操作文字成功
[2017-06-05 17:06:26 basic.lib_net] INFO 获取页面标识成功
[2017-06-05 17:06:26 basic.lib_net] INFO 获取操作文字成功
[2017-06-05 17:08:45 basic.lib_net] INFO 获取页面标识成功
[2017-06-05 17:08:45 basic.lib_net] INFO 获取操作文字成功
[2017-06-05 17:08:58 basic.lib_net] INFO 获取页面标识成功
[2017-06-05 17:08:58 basic.lib_net] INFO 获取操作文字成功
[2017-06-05 17:09:14 basic.lib_net] INFO 获取页面标识成功
[2017-06-05 17:09:14 basic.lib_net] INFO 获取操作文字成功
[2017-06-05 17:23:15 basic.lib_net] INFO 获取页面标识成功
[2017-06-05 17:23:15 basic.lib_net] INFO 获取操作文字成功
[2017-06-12 17:16:25 basic.lib_net] ERROR function invoke error: 'module' object has no attribute 'WindowDefAPI'
[2017-06-12 17:16:25 basic.lib_net] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcLib/LibNet.py", line 262, in action
    _module = self.__get_module(p_path)
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcLib/LibNet.py", line 331, in __get_module
    return getattr(__import__(self._path, fromlist=True), _name)()
AttributeError: 'module' object has no attribute 'WindowDefAPI'

[2017-06-12 17:16:26 basic.lib_net] ERROR function invoke error: 'module' object has no attribute 'WindowDefAPI'
[2017-06-12 17:16:26 basic.lib_net] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcLib/LibNet.py", line 262, in action
    _module = self.__get_module(p_path)
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcLib/LibNet.py", line 331, in __get_module
    return getattr(__import__(self._path, fromlist=True), _name)()
AttributeError: 'module' object has no attribute 'WindowDefAPI'

[2017-06-14 11:15:26 basic.lib_net] INFO 获取控件路径成功
[2017-06-14 11:15:26 basic.lib_net] INFO 获取操作文字成功
[2017-06-14 13:55:40 basic.lib_net] INFO 获取控件路径成功
[2017-06-14 13:55:40 basic.lib_net] INFO 获取操作文字成功
[2017-06-14 15:14:17 basic.lib_net] INFO 获取控件路径成功
[2017-06-14 15:14:17 basic.lib_net] INFO 获取操作文字成功
[2017-06-14 15:18:09 basic.lib_net] INFO 获取页面标识成功
[2017-06-14 15:18:09 basic.lib_net] INFO 获取操作文字成功
[2017-06-14 16:33:58 basic.lib_net] INFO 获取页面标识成功
[2017-06-14 16:33:58 basic.lib_net] INFO 获取操作文字成功
[2017-06-14 16:35:18 basic.lib_net] INFO 获取页面标识成功
[2017-06-16 13:01:55 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-06-16 13:01:55 basic.run_time] ERROR None

[2017-06-16 13:05:39 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-06-16 13:05:39 basic.run_time] ERROR None

[2017-06-16 13:05:48 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-06-16 13:05:48 basic.run_time] ERROR None

[2017-06-16 13:06:00 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-06-16 13:06:00 basic.run_time] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcDriver/Web/WebDriver.py", line 81, in start
    _result = self.__execute(_cmd)
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcDriver/Web/WebDriver.py", line 109, in __execute
    _status = self.__action(p_cmd)
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcDriver/Web/WebDriver.py", line 154, in __action
    result = _node.basic_execute(p_para)
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcDriver/Web/Widget/OrcWidget.py", line 297, in basic_execute
    self._widget.click()
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webelement.py", line 77, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webelement.py", line 493, in _execute
    return self._parent.execute(command, params)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
ElementNotInteractableException: Message: 


[2017-06-16 13:06:15 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-06-16 13:06:15 basic.run_time] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcDriver/Web/WebDriver.py", line 81, in start
    _result = self.__execute(_cmd)
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcDriver/Web/WebDriver.py", line 109, in __execute
    _status = self.__action(p_cmd)
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcDriver/Web/WebDriver.py", line 154, in __action
    result = _node.basic_execute(p_para)
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcDriver/Web/Widget/OrcWidget.py", line 297, in basic_execute
    self._widget.click()
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webelement.py", line 77, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webelement.py", line 493, in _execute
    return self._parent.execute(command, params)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
ElementNotInteractableException: Message: 


[2017-06-16 13:06:22 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-06-16 13:06:22 basic.run_time] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcDriver/Web/WebDriver.py", line 81, in start
    _result = self.__execute(_cmd)
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcDriver/Web/WebDriver.py", line 109, in __execute
    _status = self.__action(p_cmd)
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcDriver/Web/WebDriver.py", line 154, in __action
    result = _node.basic_execute(p_para)
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcDriver/Web/Widget/OrcWidget.py", line 297, in basic_execute
    self._widget.click()
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webelement.py", line 77, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webelement.py", line 493, in _execute
    return self._parent.execute(command, params)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
ElementNotInteractableException: Message: 


[2017-06-16 13:06:29 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-06-16 13:06:29 basic.run_time] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcDriver/Web/WebDriver.py", line 81, in start
    _result = self.__execute(_cmd)
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcDriver/Web/WebDriver.py", line 109, in __execute
    _status = self.__action(p_cmd)
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcDriver/Web/WebDriver.py", line 154, in __action
    result = _node.basic_execute(p_para)
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcDriver/Web/Widget/OrcWidget.py", line 297, in basic_execute
    self._widget.click()
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webelement.py", line 77, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webelement.py", line 493, in _execute
    return self._parent.execute(command, params)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
ElementNotInteractableException: Message: 


[2017-06-16 13:06:43 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-06-16 13:06:43 basic.run_time] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcDriver/Web/WebDriver.py", line 81, in start
    _result = self.__execute(_cmd)
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcDriver/Web/WebDriver.py", line 109, in __execute
    _status = self.__action(p_cmd)
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcDriver/Web/WebDriver.py", line 154, in __action
    result = _node.basic_execute(p_para)
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcDriver/Web/Widget/OrcWidget.py", line 297, in basic_execute
    self._widget.click()
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webelement.py", line 77, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webelement.py", line 493, in _execute
    return self._parent.execute(command, params)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
ElementNotInteractableException: Message: 


[2017-06-16 13:06:49 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-06-16 13:06:49 basic.run_time] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcDriver/Web/WebDriver.py", line 81, in start
    _result = self.__execute(_cmd)
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcDriver/Web/WebDriver.py", line 109, in __execute
    _status = self.__action(p_cmd)
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcDriver/Web/WebDriver.py", line 154, in __action
    result = _node.basic_execute(p_para)
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcDriver/Web/Widget/OrcWidget.py", line 297, in basic_execute
    self._widget.click()
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webelement.py", line 77, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webelement.py", line 493, in _execute
    return self._parent.execute(command, params)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
ElementNotInteractableException: Message: 


[2017-06-16 13:07:34 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-06-16 13:07:34 basic.run_time] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcDriver/Web/WebDriver.py", line 81, in start
    _result = self.__execute(_cmd)
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcDriver/Web/WebDriver.py", line 109, in __execute
    _status = self.__action(p_cmd)
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcDriver/Web/WebDriver.py", line 154, in __action
    result = _node.basic_execute(p_para)
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcDriver/Web/Widget/OrcWidget.py", line 297, in basic_execute
    self._widget.click()
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webelement.py", line 77, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webelement.py", line 493, in _execute
    return self._parent.execute(command, params)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
ElementNotInteractableException: Message: 


[2017-06-16 13:08:19 basic.run_time] ERROR 获取实时数据出错,取值为: []
