[2017-09-01 13:10:21 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-09-01 13:10:21 basic.run_time] ERROR None

[2017-09-01 14:23:11 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-09-01 14:23:11 basic.run_time] ERROR None

[2017-09-01 14:25:24 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-09-01 14:25:24 basic.run_time] ERROR None

[2017-09-01 14:27:13 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-09-01 14:27:13 basic.run_time] ERROR None

[2017-09-01 14:28:23 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-09-01 14:28:23 basic.run_time] ERROR None

[2017-09-01 14:29:18 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-09-01 14:29:18 basic.run_time] ERROR None

[2017-09-01 14:30:01 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-09-01 14:30:01 basic.run_time] ERROR None

[2017-09-01 14:30:56 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-09-01 14:30:56 basic.run_time] ERROR None

[2017-09-01 14:31:30 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-09-01 14:31:30 basic.run_time] ERROR None

[2017-09-01 14:32:39 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-09-01 14:32:39 basic.run_time] ERROR None

[2017-09-01 14:33:30 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-09-01 14:33:30 basic.run_time] ERROR None

[2017-09-01 14:39:21 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-09-01 14:39:21 basic.run_time] ERROR None

[2017-09-01 14:44:29 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-09-01 14:44:29 basic.run_time] ERROR None

[2017-09-01 14:48:28 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-09-01 14:48:28 basic.run_time] ERROR None

[2017-09-01 14:51:20 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-09-01 14:51:20 basic.run_time] ERROR None

[2017-09-04 09:26:48 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-09-04 09:26:48 basic.run_time] ERROR None

[2017-09-04 09:41:23 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-09-04 09:41:23 basic.run_time] ERROR None

[2017-09-04 09:42:33 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-09-04 09:42:33 basic.run_time] ERROR None

[2017-09-04 09:44:17 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-09-04 09:44:17 basic.run_time] ERROR None

[2017-09-04 09:54:09 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-09-04 09:54:09 basic.run_time] ERROR None

[2017-09-04 09:54:09 basic.lib_net] ERROR Error: occupy driver DRI01 failed失败, Unknown error.
[2017-09-04 09:54:09 basic.lib_net] ERROR None

[2017-09-04 09:55:07 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-09-04 09:55:07 basic.run_time] ERROR None

[2017-09-04 09:58:41 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-09-04 09:58:41 basic.run_time] ERROR None

[2017-09-04 10:02:15 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-09-04 10:02:15 basic.run_time] ERROR None

[2017-09-04 10:18:52 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-09-04 10:18:52 basic.run_time] ERROR None

[2017-09-04 10:24:06 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-09-04 10:24:06 basic.run_time] ERROR None

[2017-09-04 10:31:32 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-09-04 10:31:32 basic.run_time] ERROR None

[2017-09-04 10:42:11 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-09-04 10:42:11 basic.run_time] ERROR None

[2017-09-04 10:44:14 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-09-04 10:44:14 basic.run_time] ERROR None

[2017-09-04 13:45:47 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-09-04 13:45:47 basic.run_time] ERROR None

[2017-09-04 13:47:10 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-09-04 13:47:10 basic.run_time] ERROR None

[2017-09-04 13:51:26 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-09-04 13:51:26 basic.run_time] ERROR None

[2017-09-04 13:53:01 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-09-04 13:53:01 basic.run_time] ERROR None

[2017-09-04 13:53:59 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-09-04 13:53:59 basic.run_time] ERROR None

[2017-09-04 13:57:57 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-09-04 13:57:57 basic.run_time] ERROR None

[2017-09-04 13:58:00 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-09-04 13:58:00 basic.run_time] ERROR None

[2017-09-04 13:59:29 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-09-04 13:59:29 basic.run_time] ERROR None

[2017-09-04 14:01:40 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-09-04 14:01:40 basic.run_time] ERROR None

[2017-09-04 14:01:44 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-09-04 14:01:44 basic.run_time] ERROR None

[2017-09-04 14:07:48 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-09-04 14:07:48 basic.run_time] ERROR None

[2017-09-04 14:30:07 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-09-04 14:30:07 basic.run_time] ERROR None

[2017-09-04 14:32:28 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-09-04 14:32:28 basic.run_time] ERROR None

[2017-09-05 10:06:33 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-09-05 10:06:33 basic.run_time] ERROR None

[2017-09-05 10:21:20 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-09-05 10:21:20 basic.run_time] ERROR None

[2017-09-05 10:23:01 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-09-05 10:23:01 basic.run_time] ERROR None

[2017-09-05 10:30:55 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-09-05 10:30:55 basic.run_time] ERROR None

[2017-09-05 10:31:45 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-09-05 10:31:45 basic.run_time] ERROR None

[2017-09-05 10:33:19 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-09-05 10:33:19 basic.run_time] ERROR None

[2017-09-05 10:43:11 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-09-05 10:43:11 basic.run_time] ERROR None

[2017-09-05 10:45:14 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-09-05 10:45:14 basic.run_time] ERROR None

[2017-09-05 10:46:47 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-09-05 10:46:47 basic.run_time] ERROR None

[2017-09-05 10:47:58 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-09-05 10:47:58 basic.run_time] ERROR None

[2017-09-05 10:48:02 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-09-05 10:48:02 basic.run_time] ERROR None

[2017-09-05 11:05:34 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-09-05 11:05:34 basic.run_time] ERROR None

[2017-09-05 11:15:40 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-09-05 11:15:40 basic.run_time] ERROR None

[2017-09-05 11:16:12 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-09-05 11:16:12 basic.run_time] ERROR None

[2017-09-05 11:17:03 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-09-05 11:17:03 basic.run_time] ERROR None

[2017-09-05 11:20:00 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-09-05 11:20:00 basic.run_time] ERROR None

[2017-09-05 11:21:46 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-09-05 11:21:46 basic.run_time] ERROR None

[2017-09-05 12:58:00 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-09-05 12:58:00 basic.run_time] ERROR None

[2017-09-05 12:58:51 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-09-05 12:58:51 basic.run_time] ERROR None

[2017-09-05 12:59:16 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-09-05 12:59:16 basic.run_time] ERROR None

[2017-09-05 12:59:21 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-09-05 12:59:21 basic.run_time] ERROR None

[2017-09-05 13:01:29 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-09-05 13:01:29 basic.run_time] ERROR None

[2017-09-06 14:29:43 basic.lib_net] ERROR Socket connect localhost:5001 failed.
[2017-09-06 14:29:43 basic.lib_net] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcLib/LibNet.py", line 163, in get
    _msg = sock.recv(1024)
error: [Errno 54] Connection reset by peer

[2017-09-06 14:35:19 basic.lib_net] ERROR Socket connect localhost:5001 failed.
[2017-09-06 14:35:19 basic.lib_net] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcLib/LibNet.py", line 161, in get
    sock.connect((self._ip, self._port))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 61] Connection refused

[2017-09-06 14:36:01 basic.lib_net] ERROR Socket connect localhost:5001 failed.
[2017-09-06 14:36:01 basic.lib_net] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcLib/LibNet.py", line 161, in get
    sock.connect((self._ip, self._port))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 61] Connection refused

[2017-09-06 14:36:48 basic.lib_net] ERROR Socket connect localhost:5001 failed.
[2017-09-06 14:36:48 basic.lib_net] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcLib/LibNet.py", line 161, in get
    sock.connect((self._ip, self._port))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 61] Connection refused

[2017-09-06 14:47:09 basic.lib_net] ERROR Socket connect localhost:5001 failed.
[2017-09-06 14:47:09 basic.lib_net] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcLib/LibNet.py", line 161, in get
    sock.connect((self._ip, self._port))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 61] Connection refused

[2017-09-07 15:28:42 basic.lib_net] ERROR Invoke http://localhost:5005/api/1.0/Report failed, response is False
[2017-09-07 15:28:42 basic.lib_net] ERROR None

[2017-09-07 15:28:43 basic.lib_net] ERROR Invoke http://localhost:5005/api/1.0/Report failed, response is False
[2017-09-07 15:28:43 basic.lib_net] ERROR None

[2017-09-07 15:28:44 basic.lib_net] ERROR Invoke http://localhost:5005/api/1.0/Report failed, response is False
[2017-09-07 15:28:44 basic.lib_net] ERROR None

[2017-09-07 15:28:45 basic.lib_net] ERROR Invoke http://localhost:5005/api/1.0/Report failed, response is False
[2017-09-07 15:28:45 basic.lib_net] ERROR None

[2017-09-07 15:28:45 basic.lib_net] ERROR Invoke http://localhost:5005/api/1.0/Report failed, response is False
[2017-09-07 15:28:45 basic.lib_net] ERROR None

[2017-09-07 15:28:46 basic.lib_net] ERROR Invoke http://localhost:5005/api/1.0/Report failed, response is False
[2017-09-07 15:28:46 basic.lib_net] ERROR None

[2017-09-07 15:28:47 basic.lib_net] ERROR Invoke http://localhost:5005/api/1.0/Report failed, response is False
[2017-09-07 15:28:47 basic.lib_net] ERROR None

[2017-09-14 15:00:21 basic.lib_net] ERROR Socket connect localhost:5001 failed.
[2017-09-14 15:00:21 basic.lib_net] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcLib/LibNet.py", line 163, in get
    _msg = sock.recv(1024)
error: [Errno 4] Interrupted system call

[2017-09-14 15:21:40 basic.lib_net] ERROR Socket connect localhost:5001 failed.
[2017-09-14 15:21:40 basic.lib_net] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcLib/LibNet.py", line 163, in get
    _msg = sock.recv(1024)
error: [Errno 4] Interrupted system call

[2017-09-14 16:08:53 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-09-14 16:08:53 basic.run_time] ERROR None

[2017-09-14 16:13:57 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-09-14 16:13:57 basic.run_time] ERROR None

[2017-09-14 16:21:03 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-09-14 16:21:03 basic.run_time] ERROR None

[2017-09-14 16:21:31 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-09-14 16:21:31 basic.run_time] ERROR None

[2017-09-14 16:24:26 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-09-14 16:24:26 basic.run_time] ERROR None

[2017-09-14 16:36:31 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-09-14 16:36:31 basic.run_time] ERROR None

[2017-09-14 16:40:51 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-09-14 16:40:51 basic.run_time] ERROR None

[2017-09-14 16:41:45 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-09-14 16:41:45 basic.run_time] ERROR None

[2017-09-14 16:43:10 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-09-14 16:43:10 basic.run_time] ERROR None

[2017-09-14 16:45:40 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-09-14 16:45:40 basic.run_time] ERROR None

[2017-09-14 16:46:42 basic.process] ERROR 查询用例数据失败, None
[2017-09-14 16:46:42 basic.process] ERROR None

[2017-09-14 16:46:44 basic.process] ERROR 查询用例数据失败, None
[2017-09-14 16:46:44 basic.process] ERROR None

[2017-09-14 16:46:45 basic.process] ERROR 查询用例步骤数据失败, None
[2017-09-14 16:46:45 basic.process] ERROR None

[2017-09-14 16:46:47 basic.process] ERROR 查询步骤步骤项数据失败, None
[2017-09-14 16:46:47 basic.process] ERROR None

[2017-09-14 16:46:48 basic.process] ERROR 查询用例数据失败, None
[2017-09-14 16:46:48 basic.process] ERROR None

[2017-09-14 16:46:52 basic.process] ERROR 查询用例步骤数据失败, None
[2017-09-14 16:46:52 basic.process] ERROR None

[2017-09-14 16:46:52 basic.process] ERROR 查询用例数据失败, None
[2017-09-14 16:46:52 basic.process] ERROR None

[2017-09-14 16:47:01 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-09-14 16:47:01 basic.run_time] ERROR None

[2017-09-14 16:47:15 basic.process] ERROR 查询用例步骤数据失败, None
[2017-09-14 16:47:15 basic.process] ERROR None

[2017-09-14 16:47:17 basic.process] ERROR 查询步骤步骤项数据失败, None
[2017-09-14 16:47:17 basic.process] ERROR None

[2017-09-14 16:47:19 basic.process] ERROR 查询步骤步骤项数据失败, None
[2017-09-14 16:47:19 basic.process] ERROR None

[2017-09-14 16:47:20 basic.process] ERROR 查询用例数据失败, None
[2017-09-14 16:47:20 basic.process] ERROR None

[2017-09-14 16:47:34 basic.process] ERROR 查询用例数据失败, None
[2017-09-14 16:47:34 basic.process] ERROR None

[2017-09-14 16:48:38 basic.process] ERROR 查询用例数据失败, None
[2017-09-14 16:48:38 basic.process] ERROR None

[2017-09-14 16:49:54 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-09-14 16:49:54 basic.run_time] ERROR None

[2017-09-14 17:00:23 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-09-14 17:00:23 basic.run_time] ERROR None

[2017-09-14 17:02:37 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-09-14 17:02:37 basic.run_time] ERROR None

[2017-09-14 17:04:48 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-09-14 17:04:48 basic.run_time] ERROR None

[2017-09-14 17:05:49 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-09-14 17:05:49 basic.run_time] ERROR None

[2017-09-14 17:09:49 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-09-14 17:09:49 basic.run_time] ERROR None

[2017-09-14 17:13:20 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-09-14 17:13:20 basic.run_time] ERROR None

[2017-09-14 17:15:40 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-09-14 17:15:40 basic.run_time] ERROR None

[2017-09-14 17:17:11 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-09-14 17:17:11 basic.run_time] ERROR None

[2017-09-14 17:25:06 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-09-14 17:25:06 basic.run_time] ERROR None

[2017-09-14 17:30:35 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-09-14 17:30:35 basic.run_time] ERROR None

[2017-09-14 17:34:42 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-09-14 17:34:42 basic.run_time] ERROR None

[2017-09-14 17:40:13 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-09-14 17:40:13 basic.run_time] ERROR None

[2017-09-14 17:43:18 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-09-14 17:43:18 basic.run_time] ERROR None

[2017-09-14 17:59:38 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-09-14 17:59:38 basic.run_time] ERROR None

[2017-09-15 09:49:18 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-09-15 09:49:18 basic.run_time] ERROR None

[2017-09-15 09:52:52 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-09-15 09:52:52 basic.run_time] ERROR None

[2017-09-15 09:58:03 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-09-15 09:58:03 basic.run_time] ERROR None

[2017-09-15 09:59:09 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-09-15 09:59:09 basic.run_time] ERROR None

[2017-09-15 10:02:40 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-09-15 10:02:40 basic.run_time] ERROR None

[2017-09-15 10:04:19 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-09-15 10:04:19 basic.run_time] ERROR None

[2017-09-15 10:04:35 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-09-15 10:04:35 basic.run_time] ERROR None

[2017-09-15 10:05:42 basic.lib_net] ERROR Socket connect localhost:5001 failed.
[2017-09-15 10:05:42 basic.lib_net] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcLib/LibNet.py", line 163, in get
    _msg = sock.recv(1024)
error: [Errno 4] Interrupted system call

[2017-09-15 11:12:56 basic.lib_net.orc_resource] WARNING Path and parameter is none.
[2017-09-19 13:41:50 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-09-19 13:41:50 basic.run_time] ERROR None

[2017-09-19 17:02:35 basic.lib_net] ERROR Socket connect localhost:5001 failed.
[2017-09-19 17:02:35 basic.lib_net] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcLib/LibNet.py", line 161, in get
    sock.connect((self._ip, self._port))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 61] Connection refused

[2017-09-19 17:22:46 basic.lib_net] ERROR Socket connect localhost:5001 failed.
