[2017-05-15 13:49:51 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 334, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u'GROUP'

[2017-05-15 13:49:51 view.tree.model] ERROR select value error: batch_type, GROUP
[2017-05-15 13:49:51 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 334, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u'GROUP'

[2017-05-15 13:49:51 view.tree.model] ERROR select value error: batch_type, GROUP
[2017-05-15 13:49:51 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 334, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u'GROUP'

[2017-05-15 13:49:51 view.tree.model] ERROR select value error: batch_type, BATCH_SUIT
[2017-05-15 13:49:51 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 334, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u'BATCH_SUIT'

[2017-05-15 13:50:19 view.tree.model] ERROR select value error: batch_type, GROUP
[2017-05-15 13:50:19 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 334, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u'GROUP'

[2017-05-15 13:50:19 view.tree.model] ERROR select value error: batch_type, GROUP
[2017-05-15 13:50:19 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 334, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u'GROUP'

[2017-05-15 13:50:19 view.tree.model] ERROR select value error: batch_type, GROUP
[2017-05-15 13:50:19 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 334, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u'GROUP'

[2017-05-15 13:50:19 view.tree.model] ERROR select value error: batch_type, GROUP
[2017-05-15 13:50:19 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 334, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u'GROUP'

[2017-05-15 13:50:19 view.tree.model] ERROR select value error: batch_type, GROUP
[2017-05-15 13:50:19 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 334, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u'GROUP'

[2017-05-15 13:50:19 view.tree.model] ERROR select value error: batch_type, GROUP
[2017-05-15 13:50:19 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 334, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u'GROUP'

[2017-05-15 13:50:19 view.tree.model] ERROR select value error: batch_type, GROUP
[2017-05-15 13:50:19 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 334, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u'GROUP'

[2017-05-15 13:50:19 view.tree.model] ERROR select value error: batch_type, GROUP
[2017-05-15 13:50:19 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 334, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u'GROUP'

[2017-05-15 13:50:19 view.tree.model] ERROR select value error: batch_type, GROUP
[2017-05-15 13:50:19 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 334, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u'GROUP'

[2017-05-15 13:50:19 view.tree.model] ERROR select value error: batch_type, GROUP
[2017-05-15 13:50:19 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 334, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u'GROUP'

[2017-05-15 13:50:19 view.tree.model] ERROR select value error: batch_type, BATCH_SUIT
[2017-05-15 13:50:19 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 334, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u'BATCH_SUIT'

[2017-05-15 13:50:20 view.tree.model] ERROR select value error: batch_type, GROUP
[2017-05-15 13:50:20 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 334, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u'GROUP'

[2017-05-15 13:50:20 view.tree.model] ERROR select value error: batch_type, GROUP
[2017-05-15 13:50:20 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 334, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u'GROUP'

[2017-05-15 13:50:21 view.tree.model] ERROR select value error: batch_type, GROUP
[2017-05-15 13:50:21 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 334, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u'GROUP'

[2017-05-15 13:50:21 view.tree.model] ERROR select value error: batch_type, GROUP
[2017-05-15 13:50:21 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 334, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u'GROUP'

[2017-05-15 13:50:22 view.tree.model] ERROR select value error: batch_type, GROUP
[2017-05-15 13:50:22 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 334, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u'GROUP'

[2017-05-15 13:50:22 view.tree.model] ERROR select value error: batch_type, GROUP
[2017-05-15 13:50:22 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 334, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u'GROUP'

[2017-05-15 13:50:22 view.tree.model] ERROR select value error: batch_type, GROUP
[2017-05-15 13:50:22 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 334, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u'GROUP'

[2017-05-15 13:50:22 view.tree.model] ERROR select value error: batch_type, GROUP
[2017-05-15 13:50:22 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 334, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u'GROUP'

[2017-05-15 13:50:23 view.tree.model] ERROR select value error: batch_type, GROUP
[2017-05-15 13:50:23 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 334, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u'GROUP'

[2017-05-15 13:50:23 view.tree.model] ERROR select value error: batch_type, GROUP
[2017-05-15 13:50:23 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 334, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u'GROUP'

[2017-05-15 13:50:25 view.tree.model] ERROR select value error: batch_type, GROUP
[2017-05-15 13:50:25 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 334, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u'GROUP'

[2017-05-15 13:50:25 view.tree.model] ERROR select value error: batch_type, GROUP
[2017-05-15 13:50:25 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 334, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u'GROUP'

[2017-05-15 13:53:32 view.tree.model] ERROR select value error: batch_type, GROUP
[2017-05-15 13:53:32 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 334, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u'GROUP'

[2017-05-15 13:53:32 view.tree.model] ERROR select value error: batch_type, GROUP
[2017-05-15 13:53:32 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 334, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u'GROUP'

[2017-05-15 13:53:32 view.tree.model] ERROR select value error: batch_type, GROUP
[2017-05-15 13:53:32 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 334, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u'GROUP'

[2017-05-15 13:53:32 view.tree.model] ERROR select value error: batch_type, GROUP
[2017-05-15 13:53:32 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 334, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u'GROUP'

[2017-05-15 13:53:32 view.tree.model] ERROR select value error: batch_type, GROUP
[2017-05-15 13:53:32 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 334, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u'GROUP'

[2017-05-15 13:53:32 view.tree.model] ERROR select value error: batch_type, GROUP
[2017-05-15 13:53:32 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 334, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u'GROUP'

[2017-05-15 13:53:32 view.tree.model] ERROR select value error: batch_type, GROUP
[2017-05-15 13:53:32 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 334, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u'GROUP'

[2017-05-15 13:53:32 view.tree.model] ERROR select value error: batch_type, GROUP
[2017-05-15 13:53:32 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 334, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u'GROUP'

[2017-05-15 13:53:32 view.tree.model] ERROR select value error: batch_type, GROUP
[2017-05-15 13:53:32 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 334, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u'GROUP'

[2017-05-15 13:53:32 view.tree.model] ERROR select value error: batch_type, GROUP
[2017-05-15 13:53:32 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 334, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u'GROUP'

[2017-05-15 13:53:32 view.tree.model] ERROR select value error: batch_type, BATCH_SUIT
[2017-05-15 13:53:32 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 334, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u'BATCH_SUIT'

[2017-05-15 13:54:11 view.tree.model] ERROR select value error: batch_type, GROUP
[2017-05-15 13:54:11 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 334, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u'GROUP'

[2017-05-15 13:54:11 view.tree.model] ERROR select value error: batch_type, GROUP
[2017-05-15 13:54:11 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 334, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u'GROUP'

[2017-05-15 13:54:11 view.tree.model] ERROR select value error: batch_type, GROUP
[2017-05-15 13:54:11 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 334, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u'GROUP'

[2017-05-15 13:54:11 view.tree.model] ERROR select value error: batch_type, GROUP
[2017-05-15 13:54:11 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 334, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u'GROUP'

[2017-05-15 13:54:11 view.tree.model] ERROR select value error: batch_type, GROUP
[2017-05-15 13:54:11 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 334, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u'GROUP'

[2017-05-15 13:54:11 view.tree.model] ERROR select value error: batch_type, GROUP
[2017-05-15 13:54:11 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 334, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u'GROUP'

[2017-05-15 13:54:11 view.tree.model] ERROR select value error: batch_type, GROUP
[2017-05-15 13:54:11 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 334, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u'GROUP'

[2017-05-15 13:54:11 view.tree.model] ERROR select value error: batch_type, GROUP
[2017-05-15 13:54:11 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 334, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u'GROUP'

[2017-05-15 13:54:11 view.tree.model] ERROR select value error: batch_type, GROUP
[2017-05-15 13:54:11 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 334, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u'GROUP'

[2017-05-15 13:54:11 view.tree.model] ERROR select value error: batch_type, GROUP
[2017-05-15 13:54:11 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 334, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u'GROUP'

[2017-05-15 13:54:11 view.tree.model] ERROR select value error: batch_type, BATCH_SUIT
[2017-05-15 13:54:11 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 334, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u'BATCH_SUIT'

[2017-05-15 18:18:08 view.tree.model] ERROR select value error: batch_type, GROUP
[2017-05-15 18:18:08 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 334, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u'GROUP'

[2017-05-15 18:18:08 view.tree.model] ERROR select value error: batch_type, GROUP
[2017-05-15 18:18:08 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 334, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u'GROUP'

[2017-05-15 18:18:08 view.tree.model] ERROR select value error: batch_type, GROUP
[2017-05-15 18:18:08 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 334, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u'GROUP'

[2017-05-15 18:18:08 view.tree.model] ERROR select value error: batch_type, GROUP
[2017-05-15 18:18:08 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 334, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u'GROUP'

[2017-05-15 18:18:08 view.tree.model] ERROR select value error: batch_type, GROUP
[2017-05-15 18:18:08 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 334, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u'GROUP'

[2017-05-15 18:18:08 view.tree.model] ERROR select value error: batch_type, GROUP
[2017-05-15 18:18:08 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 334, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u'GROUP'

[2017-05-15 18:18:08 view.tree.model] ERROR select value error: batch_type, GROUP
[2017-05-15 18:18:08 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 334, in data
    return self._definition.select_def[_field.id][_value]
KeyError: u'GROUP'

