[2017-08-16 10:52:28 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:52:28 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:52:28 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:52:28 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:52:28 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:52:28 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:52:28 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:52:28 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:52:28 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:52:28 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:52:28 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:52:28 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:52:28 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:52:28 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:52:28 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:52:28 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:52:28 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:52:28 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:52:28 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:52:28 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:52:28 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:52:28 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:52:28 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:52:28 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:52:28 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:52:28 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:52:28 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:52:28 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:52:28 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:52:28 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:52:28 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:52:28 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:52:28 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:53:56 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:53:56 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:53:56 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:53:56 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:53:56 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:53:56 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:53:56 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:53:56 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:53:56 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:53:56 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:53:56 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:53:56 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:53:56 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:53:56 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:53:56 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:53:56 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:53:56 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:53:56 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:53:56 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:53:56 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:53:56 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:53:56 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:53:56 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:53:56 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:53:56 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:53:56 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:53:56 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:53:56 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:53:56 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:53:56 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:53:56 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:53:56 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:53:56 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:53:56 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:53:56 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:53:56 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:53:56 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:53:56 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:53:56 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:53:56 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:53:56 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:53:56 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:53:56 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:53:56 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:53:56 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:53:56 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:53:56 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:53:56 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:53:56 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:53:56 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:53:56 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:53:56 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:53:56 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:53:56 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:53:56 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:53:56 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:53:56 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:53:56 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:53:56 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:53:56 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:53:56 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:53:56 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:53:56 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:53:56 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:53:56 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:53:56 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:53:56 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:53:56 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:53:56 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:53:56 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:53:56 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:53:56 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:53:56 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:53:56 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:53:56 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:53:56 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:53:56 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:53:56 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:53:56 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:53:56 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:53:56 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:53:56 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:53:56 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:53:56 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:54:34 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:54:34 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:54:34 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:54:34 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:54:34 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:54:34 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:54:34 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:54:34 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:54:34 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:54:34 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:54:34 view.tree.model] ERROR Error, data is: 
