[2017-08-02 11:21:53 view.data.data_src.data_src_list_model] ERROR 查询数据源信息 {'id': u'12.TEST'}失败, None
[2017-08-02 11:21:53 view.data.data_src.data_src_list_model] ERROR None

[2017-08-02 11:21:54 view.data.data_src.data_src_list_model] ERROR 查询数据源信息 {'id': u'.TEST'}失败, None
[2017-08-02 11:21:54 view.data.data_src.data_src_list_model] ERROR None

[2017-08-02 11:21:54 view.data.data_src.data_src_list_model] ERROR 查询数据源信息 {'id': u'13.TEST'}失败, None
[2017-08-02 11:21:54 view.data.data_src.data_src_list_model] ERROR None

[2017-08-02 11:21:55 view.data.data_src.data_src_list_model] ERROR 查询数据源信息 {'id': u'.TEST'}失败, None
[2017-08-02 11:21:55 view.data.data_src.data_src_list_model] ERROR None

[2017-08-02 11:21:55 view.data.data_src.data_src_list_model] ERROR 查询数据源信息 {'id': u'14.TEST'}失败, None
[2017-08-02 11:21:55 view.data.data_src.data_src_list_model] ERROR None

[2017-08-02 11:21:56 view.data.data_src.data_src_list_model] ERROR 查询数据源信息 {'id': u'.TEST'}失败, None
[2017-08-02 11:21:56 view.data.data_src.data_src_list_model] ERROR None

[2017-08-02 11:22:46 view.data.data_src.data_src_list_model] ERROR 查询数据源信息 {'id': u'.TEST'}失败, None
[2017-08-02 11:22:46 view.data.data_src.data_src_list_model] ERROR None

[2017-08-02 11:22:46 view.data.data_src.data_src_list_model] ERROR 查询数据源信息 {'id': u'12.TEST'}失败, None
[2017-08-02 11:22:46 view.data.data_src.data_src_list_model] ERROR None

[2017-08-02 11:22:47 view.data.data_src.data_src_list_model] ERROR 查询数据源信息 {'id': u'.TEST'}失败, None
[2017-08-02 11:22:47 view.data.data_src.data_src_list_model] ERROR None

[2017-08-02 11:22:47 view.data.data_src.data_src_list_model] ERROR 查询数据源信息 {'id': u'13.TEST'}失败, None
[2017-08-02 11:22:47 view.data.data_src.data_src_list_model] ERROR None

[2017-08-02 11:35:59 view.data.data_src.data_src_list_model] ERROR 查询数据源信息 {'id': u'.TEST'}失败, None
[2017-08-02 11:35:59 view.data.data_src.data_src_list_model] ERROR None

[2017-08-02 11:35:59 view.data.data_src.data_src_list_model] ERROR 查询数据源信息 {'id': u'14.TEST'}失败, None
[2017-08-02 11:35:59 view.data.data_src.data_src_list_model] ERROR None

[2017-08-02 11:38:11 view.data.data_src.data_src_list_model] ERROR 查询数据源信息 {'id': u'.TEST'}失败, None
[2017-08-02 11:38:11 view.data.data_src.data_src_list_model] ERROR None

[2017-08-02 11:38:26 view.data.data_src.data_src_list_model] ERROR 查询数据源信息 {'id': u'.TEST'}失败, None
[2017-08-02 11:38:26 view.data.data_src.data_src_list_model] ERROR None

[2017-08-02 11:39:18 view.data.data_src.data_src_list_model] ERROR 查询数据源信息 {'id': u'.TEST'}失败, None
[2017-08-02 11:39:18 view.data.data_src.data_src_list_model] ERROR None

[2017-08-02 11:39:18 view.data.data_src.data_src_list_model] ERROR 查询数据源信息 {'id': u'13.TEST'}失败, None
[2017-08-02 11:39:18 view.data.data_src.data_src_list_model] ERROR None

[2017-08-02 12:52:59 view.data.data_src.data_src_list_model] ERROR 查询数据源信息 {'id': u'.TEST'}失败, None
[2017-08-02 12:52:59 view.data.data_src.data_src_list_model] ERROR None

[2017-08-02 12:52:59 view.data.data_src.data_src_list_model] ERROR 查询数据源信息 {'id': u'14.TEST'}失败, None
[2017-08-02 12:52:59 view.data.data_src.data_src_list_model] ERROR None

[2017-08-02 12:53:00 view.data.data_src.data_src_list_model] ERROR 查询数据源信息 {'id': u'.TEST'}失败, None
[2017-08-02 12:53:00 view.data.data_src.data_src_list_model] ERROR None

[2017-08-02 12:53:00 view.data.data_src.data_src_list_model] ERROR 查询数据源信息 {'id': u'13.TEST'}失败, None
[2017-08-02 12:53:00 view.data.data_src.data_src_list_model] ERROR None

[2017-08-02 12:53:01 view.data.data_src.data_src_list_model] ERROR 查询数据源信息 {'id': u'.TEST'}失败, None
[2017-08-02 12:53:01 view.data.data_src.data_src_list_model] ERROR None

[2017-08-02 12:53:01 view.data.data_src.data_src_list_model] ERROR 查询数据源信息 {'id': u'12.TEST'}失败, None
[2017-08-02 12:53:01 view.data.data_src.data_src_list_model] ERROR None

[2017-08-02 14:07:36 view.data.data_src.data_src_list_model] ERROR 新增数据源 % 失败失败, None
[2017-08-02 14:07:36 view.data.data_src.data_src_list_model] ERROR None

[2017-08-02 14:08:19 view.data.data_src.data_src_list_model] ERROR 新增数据源 % 失败失败, None
[2017-08-02 14:08:19 view.data.data_src.data_src_list_model] ERROR None

[2017-08-03 15:39:06 view.data.data_src.data_src_list_model] ERROR 新增数据源 % 失败失败, None
[2017-08-03 15:39:06 view.data.data_src.data_src_list_model] ERROR None

[2017-08-14 13:15:00 view.table.model] ERROR 获取 item 数据 [set(['240000018', '240000028', '240000041', '240000040'])]失败, None
[2017-08-14 13:15:00 view.table.model] ERROR None

[2017-08-16 10:50:53 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:50:53 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 249, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:50:53 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:50:53 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 249, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:50:53 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:50:53 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 249, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:50:53 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:50:53 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 249, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:50:53 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:50:53 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 249, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:50:53 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:50:53 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 249, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:50:53 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:50:53 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 249, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:50:53 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:50:53 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 249, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:50:53 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:50:53 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 249, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:50:53 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:50:53 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 249, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:50:53 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:50:53 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 249, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:50:53 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:50:53 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 249, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:50:53 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:50:53 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 249, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:50:53 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:50:53 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 249, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:50:53 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:50:53 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 249, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:50:53 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:50:53 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 249, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:50:53 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:50:53 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 249, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:50:53 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:50:53 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 249, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:50:53 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:50:53 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 249, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:50:53 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:50:53 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 249, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:50:53 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:50:53 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 249, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:50:53 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:50:53 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 249, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:50:54 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:50:54 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 249, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:50:54 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:50:54 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 249, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:50:54 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:50:54 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 249, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:50:54 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:50:54 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 249, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:50:54 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:50:54 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 249, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:50:54 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:50:54 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 249, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:50:54 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:50:54 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 249, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:50:54 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:50:54 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 249, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:50:54 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:50:54 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 249, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:50:54 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:50:54 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 249, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:50:54 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:50:54 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 249, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:50:54 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:50:54 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 249, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:50:54 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:50:54 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 249, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:50:54 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:50:54 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 249, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:50:54 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:50:54 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 249, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:50:54 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:50:54 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 249, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:50:54 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:50:54 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 249, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:50:54 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:50:54 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 249, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:50:54 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:50:54 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 249, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:50:54 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:50:54 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 249, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:50:54 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:50:54 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 249, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:52:28 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:52:28 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:52:28 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:52:28 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:52:28 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:52:28 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:52:28 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:52:28 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:52:28 view.tree.model] ERROR Error, data is: 
[2017-08-16 10:52:28 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 250, in data
    _value = item.content[_field.id]
KeyError: None

[2017-08-16 10:52:28 view.tree.model] ERROR Error, data is: 
