[2017-07-21 17:59:37 basic.run_time] ERROR None

[2017-07-21 17:59:37 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-07-21 17:59:37 basic.run_time] ERROR None

[2017-07-21 18:00:57 basic.lib_net] ERROR Connect to socket server(127.0.0.1:5001) Failed
[2017-07-21 18:00:57 basic.lib_net] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcLib/LibNet.py", line 193, in get
    sock.connect((self._ip, self._port))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 61] Connection refused

[2017-07-21 18:00:57 basic.lib_net] ERROR Error: occupy driver DRI01 failed失败, None
[2017-07-21 18:00:57 basic.lib_net] ERROR None

[2017-07-21 18:02:41 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-07-21 18:02:41 basic.run_time] ERROR None

[2017-07-21 18:02:41 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-07-21 18:02:41 basic.run_time] ERROR None

[2017-07-24 16:20:31 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-07-24 16:20:31 basic.run_time] ERROR None

[2017-07-24 16:20:31 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-07-24 16:20:31 basic.run_time] ERROR None

[2017-07-24 16:55:12 basic.lib_net] ERROR Error: occupy driver DRI02 failed失败, 未知命令类型
[2017-07-24 16:55:12 basic.lib_net] ERROR None

[2017-07-24 17:02:00 basic.lib_net] ERROR Error: occupy driver DRI01 failed失败, 未知命令类型
[2017-07-24 17:02:00 basic.lib_net] ERROR None

[2017-07-24 17:02:29 basic.lib_net] ERROR Error: occupy driver DRI01 failed失败, 未知命令类型
[2017-07-24 17:02:29 basic.lib_net] ERROR None

[2017-07-24 17:02:41 basic.lib_net] ERROR Error: occupy driver DRI01 failed失败, 未知命令类型
[2017-07-24 17:02:41 basic.lib_net] ERROR None

[2017-07-24 17:02:47 basic.lib_net] ERROR Error: occupy driver DRI01 failed失败, 未知命令类型
[2017-07-24 17:02:47 basic.lib_net] ERROR None

[2017-07-24 17:03:24 basic.lib_net] ERROR Error: occupy driver DRI01 failed失败, 未知命令类型
[2017-07-24 17:03:24 basic.lib_net] ERROR None

[2017-07-24 17:14:51 basic.lib_net] ERROR Error: occupy driver DRI01 failed失败, 未知命令类型
[2017-07-24 17:14:51 basic.lib_net] ERROR None

[2017-07-24 17:18:07 basic.lib_net] ERROR Error: occupy driver DRI01 failed失败, 未知命令类型
[2017-07-24 17:18:07 basic.lib_net] ERROR None

[2017-07-24 17:19:36 basic.lib_net] ERROR Error: occupy driver DRI01 failed失败, 未知命令类型
[2017-07-24 17:19:36 basic.lib_net] ERROR None

[2017-07-24 17:25:57 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-07-24 17:25:57 basic.run_time] ERROR None

[2017-07-24 17:25:57 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-07-24 17:25:57 basic.run_time] ERROR None

[2017-07-24 17:28:16 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-07-24 17:28:16 basic.run_time] ERROR None

[2017-07-24 17:28:16 basic.run_time] ERROR 获取实时数据出错,取值为: []
[2017-07-24 17:28:16 basic.run_time] ERROR None

[2017-08-05 16:52:22 basic.lib_net] ERROR function invoke error: No module named Database.DataBaseApi
[2017-08-05 16:52:22 basic.lib_net] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcLib/LibNet.py", line 284, in action
    _module = self.__get_module(p_path)
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcLib/LibNet.py", line 353, in __get_module
    return getattr(__import__(self._path, fromlist=True), _name)()
ImportError: No module named Database.DataBaseApi

[2017-08-05 16:53:03 basic.lib_net] ERROR function invoke error: No module named DataBaseApi
[2017-08-05 16:53:03 basic.lib_net] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcLib/LibNet.py", line 284, in action
    _module = self.__get_module(p_path)
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcLib/LibNet.py", line 353, in __get_module
    return getattr(__import__(self._path, fromlist=True), _name)()
ImportError: No module named DataBaseApi

[2017-08-05 16:53:15 basic.lib_net] ERROR function invoke error: 'module' object has no attribute 'DataBaseAPI'
[2017-08-05 16:53:15 basic.lib_net] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcLib/LibNet.py", line 284, in action
    _module = self.__get_module(p_path)
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcLib/LibNet.py", line 353, in __get_module
    return getattr(__import__(self._path, fromlist=True), _name)()
AttributeError: 'module' object has no attribute 'DataBaseAPI'

[2017-08-05 16:55:46 basic.lib_net] ERROR function invoke error: 'module' object has no attribute 'DataBaseAPI'
[2017-08-05 16:55:46 basic.lib_net] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcLib/LibNet.py", line 284, in action
    _module = self.__get_module(p_path)
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcLib/LibNet.py", line 353, in __get_module
    return getattr(__import__(self._path, fromlist=True), _name)()
AttributeError: 'module' object has no attribute 'DataBaseAPI'

[2017-08-05 16:57:24 basic.lib_net] ERROR function invoke error: 'module' object has no attribute 'DataBaseAPI'
[2017-08-05 16:57:24 basic.lib_net] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcLib/LibNet.py", line 284, in action
    _module = self.__get_module(p_path)
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcLib/LibNet.py", line 353, in __get_module
    return getattr(__import__(self._path, fromlist=True), _name)()
AttributeError: 'module' object has no attribute 'DataBaseAPI'

[2017-08-05 16:59:03 basic.lib_net] ERROR function invoke error: cannot import name DataBaseBus
[2017-08-05 16:59:03 basic.lib_net] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcLib/LibNet.py", line 284, in action
    _module = self.__get_module(p_path)
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcLib/LibNet.py", line 353, in __get_module
    return getattr(__import__(self._path, fromlist=True), _name)()
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcApi/DataBase/DataBaseApi.py", line 4, in <module>
    from .DataBaseBus import DataBaseBus
ImportError: cannot import name DataBaseBus

